---

#
# variables shared in baselayout
#

git_no_binpkg: ['debian7']
git_version: 2.10.2

ssh_config: /etc/ssh/sshd_config

sshd_service_map: {
  'ubuntu1404': 'ssh',
  'smartos17': 'ssh',
  'smartos18': 'ssh',
}

sshd_service_name: "{{ sshd_service_map[os]|default(sshd_service_map[os|stripversion])|default('sshd') }}"

ntp_service: {
  systemd: ['debian8', 'debian9', 'debian10', 'ubuntu1604', 'ubuntu1804'],
  ntp_package: ['ubuntu1404']
}

common_packages: [
  'automake,bash,libtool',
]

# You can either add os family or os to this list (see smartos)
# but the playbook chooses os over family - not both.
#
# To determine the value of `os` or of `arch` for a specific HOST, use ansible:
# % ansible -m debug -a "var=arch"  HOST
# % ansible -m debug -a "var=os"  HOST
packages: {
  centos6_x64: ['centos-release-scl'], # only available on x86_64, 32-bit is from https://copr.fedorainfracloud.org/coprs/mlampe
  centos6: [
    'ccache,git2u,gcc-c++,devtoolset-6,sudo', # even need gcc on centos6 so ccache has symlinks
  ],

  # centos-release-scl is required to enable SCLo but we do it manually in
  # partials/repo/centos7.yml for arm64
  centos7_arm64: ['git'], # git2u not available for aarch64 (yet)
  centos7_x64: ['devtoolset-6-libatomic-devel,git222,centos-release-scl,python3'],
  centos7_ppc64: ['cmake3,devtoolset-6-libatomic-devel,git,python3'],

  centos7: [
    'bzip2-devel,openssl-devel,ccache,gcc-c++,devtoolset-6,sudo,zlib-devel,libffi-devel,devtoolset-8,devtoolset-8-libatomic-devel',
  ],

  aix: [
    'bash,cmake,curl,gcc-c++,gcc6-c++,tar,unzip,git,make,sudo,python-setuptools,python3',
  ],

  ibmi: [
    'autoconf,automake,ca-certificates-mozilla,ccache,cmake,coreutils-gnu,gcc,gcc-cplusplus,gcc-cpp,git,libstdcplusplus-devel,m4-gnu,openssl-devel,python3,python3-pip,sed-gnu,zlib-devel',
  ],

  debian7: [
    'gcc-4.8,g++-4.8,sudo',
  ],

  debian8: [
    'ccache,git,gcc-4.9,g++-4.9,libfontconfig1,binutils-2.26,sudo',
  ],

  debian9: [
    'gcc-6,g++-6,ccache,git,curl,libfontconfig1,apt-transport-https,ca-certificates,sudo',
  ],

  debian10: [
    'gcc-8,g++-8,ccache,git,curl,libfontconfig1,apt-transport-https,ca-certificates,sudo,python3-pip',
  ],

  fedora: [
    'bzip2,ccache,gcc-c++,git,fontconfig,sudo,make',
  ],

  freebsd: [
    'ccache,git,gmake,sudo,python3,py36-pip'
  ],

  'macos10.10': [
    'cmake,python,ccache'
  ],

  'macos10.11': [
    'cmake,python,ccache'
  ],

  'macos10.12': [
    'cmake,python,ccache'
  ],

  'macos10.13': [
    'cmake,python,ccache'
  ],


  'macos10.14': [
    'cmake,python,ccache'
  ],


  'macos10.15': [
    'cmake,python,ccache'
  ],

  'macos10.16': [
    'cmake,python,ccache'
  ],

  'macos11.0': [
    'cmake,python,ccache'
  ],

  rhel7: [
    'gcc-c++,sudo,git,zip,unzip,iptables-services,GConf2-devel,openssl-devel,python3',
  ],

  smartos: [
    'gccmakedep',
    'git',
    'gmake',
    'xz',
    'sudo',
  ],

  smartos15: [
    'gcc49',
    'gcc49-libs'
  ],

  smartos16: [
    'gcc49',
    'gcc49-libs'
  ],

  smartos17: [
    'gcc7',
    'python36'
  ],

  smartos18: [
    'gcc7',
    'ccache',
    'python37'
  ],

  ubuntu: [
    'ccache,g++,gcc,g++-6,gcc-6,git,libfontconfig1,sudo,python3-pip',
  ],

  ubuntu1404: [
    'ntp,gcc-8,g++-8,gcc-6,g++-6,g++-4.8,gcc-4.8,g++-4.9,gcc-4.9,binutils-2.26',
  ]
}
